### ISSUE TITLE
Cryptographic issues

### ISSUE THREAD

**Issue by mcpherrinm** [Merkoba/Effer#1]
Hi, saw this project via reddit.

I haven't tried it out, but just saw a few basic cryptographic issues when reading the code.

1. Use of key = sha3(password)
Unless the user's password is a long, randomly-generated password (which is not a good assumption to make), this is vulnerable to brute-forcing.  From Latacora's "Cryptographic right answers" post, use scrypt, argon2, bcrypt, and then if nothing else is available PBKDF2.
These algorithms all deliberately use a lot of computational power to avoid bruteforce attacks.
In the reddit post, somebody suggested crypto_pwhash, which uses argon2.  That would be a good idea.

2.  Non-random IVs
You use an IV which depends only on the key, which means you will always use the same IV for all files using the same key.  
You have a code comment which suggests doing the right thing, but is not what you've done:  You should randomly generate a new IV each time you encrypt the file.  Usually the IV would be included alongside the ciphertext; easiest is to just put it at the start.

3. Non-authenticated ciphertexts.  Maybe not a big deal in this context, but it's a good property to validate the ciphertext hasn't been modified generally.  Best option here is to use an AEAD mode that gives you that for free, or AES-CBC + HMAC.  Note that reusing IVs (as you are) with AES-GCM (an AEAD mode) is disastrous;  address (2) before thinking about (3).

**Comment by madprops** [comment]
Thanks the input. I will look into this more carefully tomorrow.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by madprops** [comment]
I made some changes. Now GCM is used instead of CBC. The salt is generated randomly on each encryption and placed on the file. Decryption involves making the same key used in encryption using the same and password, and then using that key to decrypt through AESGCM256. You can check what happens in https://github.com/Merkoba/Effer/blob/master/src/encryption.rs

Wondering if you could give it a look before I make a 2.0 release ?

**Comment by madprops** [comment]
Right now it seems to me it's not really secure since the salt is available in plain text. There has to be a better way

**Comment by mcpherrinm** [comment]
Salt for the password hash in the plain is OK:  The point of the salt in the password hash is to prevent pre-computation.  Say you have 100 users of this software; an attacker must brute force all 100 users separately instead of being able to brute force them all together, or ahead of time.

    let nonce = GenericArray::from_slice(b"unique nonce"); 
this should be random, not just "unique nonce"; it must actually be unique.  

Since you are already using the sodiumoxide crate, I would recommend using sodiumoxide::secretbox instead of the aes_gcm crate.  It has a secretbox::gen_nonce() function which will generate a random nonce successfully.  You should generate a new nonce each time you encrypt the file.

**Comment by madprops** [comment]
Thanks. I was told that, since I'm making a new key every time, the nonce wasn't that important since it just acted as an ID to reuse keys, but idk. I now use a random nonce by generating a random 12 char string (I had some trouble using gen_nonce()). The nonce is put in the file along the salt. I'll leave this open a couple of days in case I'm doing something terribly wrong, before I release v2.0.0

**Comment by KellerFuchs** [comment]
> I now use a random nonce by generating a random 12 char string

For reference, the code in question:
```rust
    let mut rng = thread_rng();

    let chars: String = iter::repeat(())
        .map(|()| rng.sample(Alphanumeric))
        .take(12)
        .collect();

    chars
```

@madprops The string that `generate_nonce()` produces only has 12*log₂(2*26 +10) ≃ 71 bits of entropy (assuming `rand` implements a secure RNG and correct, uniform sampling), which is insufficient to guarantee with high probability that random nonces do not get reused.

(Moreover, it is much easier to get it right by generating a uniform value in the target set, like `secretbox::get_nonce()` does, and then (if a raw byte slice is inappropriate), encoding it to whatever representation is deemed appropriate; since you have `base64::encode` around anyhow, you could use that if plain binary data isn't to your liking.)


Secondly, you are still using `aes_gcm` rather than `sodiumoxide::secretbox` (though you store the key used by `aes_gcm` in a `secretbox::Key`); the latter is designed to provide robust encryption with a hard-to-misuse API, and as @mcpherrinm mentioned you should prefer that.


Kind of an aside, but the use of the first line of the plaintext as a header that must start with `UNLOCK_CHECK` is unnecessary: if the wrong password is provided, the wrong key will be derived, resulting in a decryption error (now that you use an AEAD mode).

**Comment by madprops** [comment]
Thanks. I'll check this tomorrow.

**Comment by KellerFuchs** [comment]
OK; for what it's worth, I was able to write pretty quickly a replacement of that crypto code purely in terms of `sodiumoxyde`, but I didn't try to improve the API used by the rest of the crate, nor did I write tests.

**Comment by madprops** [comment]
About the nonce, since I'm making a new key every time, collisions wouldn't be important.
Secretbox's seel seems to use `xsalsa20poly1305`, and I wonder if that would be better than GCM or if you had another function in mind. 
Would be interesting to see your code.

**Comment by KellerFuchs** [comment]
> About the nonce, since I'm making a new key every time, collisions wouldn't be important.

This is currently correct, but using a fixed nonce is much more *fragile*:
- It relies on the password salt generation being done correctly, and the keys derived from the passwords never colliding.
- There are optimizations you might chose to implement in the future that would break it.  
  For instance, if you wanted to avoid a call to `pwhash::derive_key_interactive` every time you save a file with the same password (might be handy for autosave and such), you'd have to reuse the same salt (and derived key); on its own, this is a perfectly legitimate thing to do, but combined with a static “nonce” it would break the AEAD guarantees.


> Secretbox's seal seems to use `xsalsa20poly1305`, and I wonder if that would be better than GCM or if you had another function in mind.

I left the default choice of cryptosystem (indeed `xsalsa20poly1305`), which provides pretty-much the same authenticated encryption guarantees as AES-GCM; there are some relatively-minor reasons to prefer it:
- pure-software AES-GCM implementations (including the one you are using from `aes_gcm`) are vulnerable to timing- and cache-based attacks; while I doubt it is very relevant for Effer, it's better (and easier to reason about) to simply not have the issue;
- the default `secretbox` remains safe to use (with a single key) for larger volumes of data than AES-GCM; again, this likely isn't relevant for Effer, since keys are expected to be unique per file, and individual files are very-unlikely to grow to multi-gigabytes sizes (which is way below the bounds for the safe use of either AES-GCM or `secretbox`)


> Would be interesting to see your code.

Sent as pull request #2; as stated in the description, it's not necessarily in a mergeable state as-is (no tests, suboptimal serialisation path, ...)
